/*
 * StatsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.dcsa.api.stats;

import io.apimatic.core.utilities.CoreHelper;

/**
 * This is a Helper class with commonly used utilities for the SDK.
 */
public class ApiHelper extends CoreHelper {

}