/*
 * StatsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.dcsa.api.stats;

import io.apimatic.core.utilities.LocalDateTimeHelper;

/**
 * This is a utility class for DateTime operations.
 */
public class DateTimeHelper extends LocalDateTimeHelper {

}