/*
 * StatsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.dcsa.api.stats.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.util.UUID;
import org.dcsa.api.stats.ApiHelper;
import org.dcsa.api.stats.StatsAPIClient;
import org.dcsa.api.stats.exceptions.ApiException;
import org.dcsa.api.stats.models.V1StatsRequest;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class RealTimeControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static StatsAPIClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static RealTimeController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getRealTimeController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * This endpoint allows you to report the usage statistics of a reference API call. .
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestPostV1Stats() throws Exception {
        // Parameters for the API call
        UUID dCSAAPIKEY = UUID.fromString(
                "055409d4-c69a-403f-8cca-d950fc11b12b");
        V1StatsRequest body = null;

        // Set callback and perform API call
        try {
            controller.postV1Stats(dCSAAPIKEY, body);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 204", 
                204, httpResponse.getResponse().getStatusCode());

    }

}
